fix: Docker compose command in workflow

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -15,16 +15,20 @@ jobs:
         node-version: 18
     
     - name: Docker compose environment
-      run: docker-compose --env-file .env.ci up -d
+      run: docker-compose --env-file .env.ci -f docker-compose.ci.yml up -d
 
     - name: Wait for server and containers to be ready
       run: |
         echo "Waiting for server and containers to be ready..."
         timeout=180 # 180 seconds (3 minutes)
         elapsed=0
-        until [ "$(docker-compose ps | grep 'Up' | wc -l)" -eq 3 ] && curl --output /dev/null --silent --head --fail http://localhost:8199; do
+        until curl --output /dev/null --silent --head --fail http://localhost:8199; do
+            if [ "$(docker-compose ps | grep 'Up' | wc -l)" -ne 3 ]; then
+                echo "Number of 'Up' containers is not 3. Failing the workflow."
+                exit 1
+            fi
             if [ $elapsed -ge $timeout ]; then
-                echo "Server or containers did not become ready in time. Failing the workflow."
+                echo "Server did not become ready in time. Failing the workflow."
                 exit 1
             fi
             printf '.'
